baseURL = 'https://phenix66.github.io/'
languageCode = 'en-us'
title = 'Phenix66 - GitHub Pages'

[module]
[[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[outputs]
    home = [ "HTML", "RSS", "SEARCH"]
